# Generated by Django 4.2.5 on 2023-10-04 20:13

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, unique=True),
        ),
    ]
