# Generated by Django 4.2.5 on 2023-10-03 20:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_per_installment', models.DecimalField(decimal_places=2, max_digits=4)),
                ('number_of_installments', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=24)])),
                ('installment_value', models.IntegerField()),
                ('total_value', models.IntegerField()),
                ('comission', models.IntegerField()),
                ('card_number', models.CharField(max_length=16)),
                ('card_cvc', models.CharField(max_length=3)),
                ('card_validity', models.CharField(max_length=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
