# Generated by Django 4.2.5 on 2023-10-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitations',
            name='desired_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
