# Generated by Django 4.2.5 on 2023-10-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0002_solicitations_desired_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitations',
            name='interest_per_installment',
            field=models.IntegerField(),
        ),
    ]
