# Generated by Django 4.2.5 on 2023-10-04 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0004_alter_solicitations_interest_per_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitations',
            name='desired_value',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=10000), django.core.validators.MinValueValidator(limit_value=300)]),
        ),
        migrations.AlterField(
            model_name='solicitations',
            name='interest_per_installment',
            field=models.IntegerField(),
        ),
    ]
