# Generated by Django 4.2.5 on 2023-10-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0005_alter_solicitations_desired_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitations',
            name='card_validity',
            field=models.DateField(),
        ),
    ]
