# Generated by Django 4.2.5 on 2023-10-04 20:30

from django.db import migrations, models
import solicitations.models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0006_alter_solicitations_card_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitations',
            name='card_validity',
            field=models.CharField(max_length=5, validators=[solicitations.models.validate_month_year_format]),
        ),
    ]
