# Generated by Django 4.2.5 on 2023-10-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0007_alter_solicitations_card_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitations',
            name='table',
            field=models.CharField(choices=[('Default', 'Default'), ('Partner', 'Partner')], default='Default', max_length=20),
        ),
    ]
