# Generated by Django 4.2.5 on 2023-10-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0008_solicitations_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitations',
            name='contract',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatico', 'Automatico')], default='Manual'),
        ),
    ]
