# Generated by Django 4.2.5 on 2023-10-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0009_solicitations_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitations',
            name='contract',
        ),
    ]
