# Generated by Django 4.2.5 on 2023-10-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0010_remove_solicitations_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitations',
            name='contract',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatico', 'Automatico')], default='Manual'),
        ),
    ]
